// Generated by Xata Codegen 0.29.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "pages",
    columns: [
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "userId", type: "link", link: { table: "users" } },
      { name: "pictureUrl", type: "file", file: { defaultPublicAccess: true } },
    ],
    revLinks: [{ column: "pageId", table: "links" }],
  },
  { name: "socials", columns: [] },
  {
    name: "links",
    columns: [
      { name: "title", type: "text" },
      { name: "url", type: "text" },
      { name: "linkViews", type: "int", defaultValue: "0" },
      { name: "pageId", type: "link", link: { table: "pages" } },
    ],
  },
  {
    name: "users",
    columns: [
      { name: "email", type: "string", unique: true },
      { name: "username", type: "string", unique: true },
      { name: "password", type: "text" },
    ],
    revLinks: [{ column: "userId", table: "pages" }],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Pages = InferredTypes["pages"];
export type PagesRecord = Pages & XataRecord;

export type Socials = InferredTypes["socials"];
export type SocialsRecord = Socials & XataRecord;

export type Links = InferredTypes["links"];
export type LinksRecord = Links & XataRecord;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type DatabaseSchema = {
  pages: PagesRecord;
  socials: SocialsRecord;
  links: LinksRecord;
  users: UsersRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://teresalee-v3roq0.us-east-1.xata.sh/db/OhMyLink",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
